# Generated by Django 3.2.6 on 2021-09-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_to_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_to_Cart',
            new_name='Cart',
        ),
    ]
